### ISSUE TITLE
Missing dependency tslib

### ISSUE THREAD

**Issue by cloudwheels** [Zilliqa/Zilliqa-JavaScript-Library#167]
**Describe the bug**
Missing dependency `tslib` (package `@zilliqa-js/zilliqa`)

**To Reproduce**
Create Node v.10.0 project using example code from README.md as index.js

```
$ node -v
v10.0.0
```
```
$ yarn init
yarn init v1.17.3
...
```
```
$ yarn add @zilliqa-js/zilliqa
...
```
create `index.js` using sample code
```
$ node .
internal/modules/cjs/loader.js:573
    throw err;
    ^

Error: Cannot find module 'tslib'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/nigel/Zilliqa-Node-Starter-Basic/node_modules/@zilliqa-js/util/dist/index.js:17:15)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
```

`yarn add tslib` to resolve error:

```
$ yarn add tslib
yarn add v1.17.3
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ tslib@1.10.0
info All dependencies
└─ tslib@1.10.0
Done in 4.74s.
```

```
$ node .
My account address is: 0x4d2593679d0367C07F5a9Cb906357FC2B23be25e
My account bech32 address is: zil1f5jexeuaqdnuql66njusvdtlc2erhcj72qpdv8
...
```

**Comment by edisonljh** [comment]
Closing.

**Comment by balthazar** [comment]
@edisonljh Still having this issue when only installing @zilliqa-js/account
