### ISSUE TITLE
README.md : "Quickstart" reports error although the setHello transition was successful:

### ISSUE THREAD

**Issue by SvenMeyer** [Zilliqa/Zilliqa-JavaScript-Library#187]
"Quickstart" (testBlockchain contract + JavaScript) on README.md reports error 
although the setHello transition was successful:

node : v10.17.0
@zilliqa-js/zilliqa@0.8.7

```
$ node testBlockchain.js 
My account address is: 0x0bA87F4374F7d9fe3ddf75b11439506b491A779a
My account bech32 address is: zil1pw587sm57lvlu0wlwkc3gw2sddy35au6esw589
Your account balance is:
{ balance: '199142999775114', nonce: 118 }
Current Minimum Gas Price: 1000000000
My Gas Price 1000000000
Is the gas price sufficient? true
Sending a payment transaction to the network...
The transaction status is:
{ cumulative_gas: 1, epoch_num: '970850', success: true }
Deploying a new contract....
Deployment Transaction ID: 4ad761133ac154e662d23552c8840db9a9073ea1283e4ffded066c8a693bcd7d
Deployment Transaction Receipt:
{ cumulative_gas: 2550, epoch_num: '970853', success: true }
The contract address is:
0x8aF19E1F668C1a7c0A960659ef76A9Ff2D4C442d
Calling setHello transition with msg: Hello, the time is 1576307077109
Error: The transaction is still not confirmed after 33 attempts.
    at Transaction.<anonymous> (/home/sum/zilliqa/ipfs_asset_viewer/node_modules/@zilliqa-js/account/dist/transaction.js:329:31)
    at step (/home/sum/zilliqa/ipfs_asset_viewer/node_modules/tslib/tslib.js:136:27)
    at Object.next (/home/sum/zilliqa/ipfs_asset_viewer/node_modules/tslib/tslib.js:117:57)
    at fulfilled (/home/sum/zilliqa/ipfs_asset_viewer/node_modules/tslib/tslib.js:107:62)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
https://viewblock.io/zilliqa/address/zil13tceu8mx3sd8cz5kqev77a4fluk5c3pdjj906k?network=testnet

**Comment by SvenMeyer** [comment]
changing the call parameter (in line 178) from `100` to `1000` "solves" the problem:
```
...
      },
      33,
      1000,
      false,
    );
```

**Comment by renlulu** [comment]
Hey, that's dependent on the confirmation time of your transaction, not a exact error. If you want to get your transaction id anyway(in case you want to track it via viewblock or API), can refer https://github.com/Zilliqa/Zilliqa-JavaScript-Library/blob/dev/examples/helloWord.js#L46.
